/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-glass': 'var(--color-bg-glass)',
        'bg-glass-light': 'var(--color-bg-glass-light)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        terrorist: 'var(--color-terrorist)',
        'terrorist-glow': 'var(--color-terrorist-glow)',
        counter: 'var(--color-counter)',
        'counter-glow': 'var(--color-counter-glow)',
        'health-full': 'var(--color-health-full)',
        'health-mid': 'var(--color-health-mid)',
        'health-low': 'var(--color-health-low)',
        'health-critical': 'var(--color-health-critical)',
        armor: 'var(--color-armor)',
        money: 'var(--color-money)',
        'ammo-full': 'var(--color-ammo-full)',
        'ammo-low': 'var(--color-ammo-low)',
        'ammo-reload': 'var(--color-ammo-reload)',
        'damage-vignette': 'var(--color-damage-vignette)',
        'heal-vignette': 'var(--color-heal-vignette)',
        'flash-white': 'var(--color-flash-white)',
        'smoke-overlay': 'var(--color-smoke-overlay)',
        'accent-gold': 'var(--color-accent-gold)',
        'accent-purple': 'var(--color-accent-purple)',
        'accent-cyan': 'var(--color-accent-cyan)',
      },
      fontFamily: {
        display: ['Rajdhani', 'Inter', 'sans-serif'],
        mono: ['Roboto Mono', 'Courier New', 'monospace'],
        sans: ['Inter', 'Segoe UI', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
      },
      animation: {
        'slide-in-right':
          'slide-in-right 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'slide-in-left': 'slide-in-left 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'slide-in-up': 'slide-in-up 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'slide-in-down': 'slide-in-down 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'fade-out': 'fade-out 0.3s cubic-bezier(0, 0, 0.2, 1) forwards',
        'fade-in': 'fade-in 0.3s cubic-bezier(0.4, 0, 1, 1)',
        'pulse-glow': 'pulse-glow 1s ease-in-out infinite',
        'pulse-border': 'pulse-border 1s ease-in-out infinite',
        'pulse-scale': 'pulse-scale 1s ease-in-out infinite',
        'damage-flash': 'damage-flash 0.2s ease-out',
        'damage-indicator': 'damage-indicator 0.5s ease-out',
        'panic-glow': 'panic-glow 0.5s ease-in-out infinite',
        'reload-progress': 'reload-progress 2s linear forwards',
        'hit-confirm': 'hit-confirm 0.15s ease-out',
        'kill-flash': 'kill-flash 0.3s ease-out',
        shake: 'shake 0.3s ease-out',
        float: 'float 10s ease-in-out infinite',
      },
      keyframes: {
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-left': {
          from: { opacity: '0', transform: 'translateX(-30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-up': {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-down': {
          from: { opacity: '0', transform: 'translateY(-30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-out': {
          from: { opacity: '1' },
          to: { opacity: '0' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 5px var(--color-health-low)' },
          '50%': {
            boxShadow:
              '0 0 20px var(--color-health-low), 0 0 40px var(--color-health-low)',
          },
        },
        'pulse-border': {
          '0%, 100%': { borderColor: 'rgba(239, 68, 68, 0.3)' },
          '50%': { borderColor: 'rgba(239, 68, 68, 0.8)' },
        },
        'pulse-scale': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.05)', opacity: '0.8' },
        },
        'damage-flash': {
          '0%': { backgroundColor: 'rgba(239, 68, 68, 0.2)' },
          '100%': { backgroundColor: 'transparent' },
        },
        'damage-indicator': {
          '0%': { opacity: '0', transform: 'translateY(10px) scale(0.8)' },
          '50%': { opacity: '1', transform: 'translateY(0) scale(1)' },
          '100%': { opacity: '0', transform: 'translateY(-10px) scale(0.8)' },
        },
        'panic-glow': {
          '0%, 100%': {
            boxShadow: '0 0 10px rgba(239, 68, 68, 0.3)',
            borderColor: 'rgba(239, 68, 68, 0.3)',
          },
          '50%': {
            boxShadow:
              '0 0 30px rgba(239, 68, 68, 0.6), 0 0 60px rgba(239, 68, 68, 0.2)',
            borderColor: 'rgba(239, 68, 68, 0.8)',
          },
        },
        'reload-progress': {
          from: { width: '0%' },
          to: { width: '100%' },
        },
        'hit-confirm': {
          '0%': { opacity: '0', transform: 'scale(0.5)' },
          '30%': { opacity: '1', transform: 'scale(1.2)' },
          '100%': { opacity: '0', transform: 'scale(1)' },
        },
        'kill-flash': {
          '0%': { backgroundColor: 'rgba(255, 215, 0, 0.2)' },
          '100%': { backgroundColor: 'transparent' },
        },
        shake: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '10%': { transform: 'translate(-2px, -2px)' },
          '20%': { transform: 'translate(2px, 2px)' },
          '30%': { transform: 'translate(-2px, 2px)' },
          '40%': { transform: 'translate(2px, -2px)' },
          '50%': { transform: 'translate(-1px, 1px)' },
          '60%': { transform: 'translate(1px, -1px)' },
          '70%': { transform: 'translate(-1px, -1px)' },
          '80%': { transform: 'translate(1px, 1px)' },
          '90%': { transform: 'translate(-1px, 0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-20px) translateX(10px)' },
          '50%': { transform: 'translateY(-10px) translateX(-10px)' },
          '75%': { transform: 'translateY(-30px) translateX(5px)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
        dramatic: 'var(--duration-dramatic)',
      },
    },
  },
  plugins: [],
}
